-- DML UNIVERSO DA LEITURA
-- INSERIR 5 ASSOCIADOS

INSERT INTO ASSOCIADOS (CODID_, RG, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES (1, 2447897, 'MARCOS', 'SILVA', 'RUA ALAMEDA', 'SOROCABA', 'SP');
INSERT INTO ASSOCIADOS (CODID_, RG, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES (2, 6573839, 'ELAINE', 'SILVA', 'RUA ALAMEDA', 'SOROCABA', 'SP');
INSERT INTO ASSOCIADOS (CODID_, RG, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES (3, 7584939, 'CAROL', 'MARTINS', 'RUA REGINA', 'SOROCABA', 'SP');
INSERT INTO ASSOCIADOS (CODID_, RG, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES (4, 4273900, 'MARISA', 'DANI', 'RUA RESERVA', 'SOROCABA', 'SP');
INSERT INTO ASSOCIADOS (CODID_, RG, NOME, SOBRENOME, ENDERECO, CIDADE, ESTADO)
VALUES (5, 6583920, 'JOSE', 'MARTINS', 'RUA BOSQUE', 'SOROCABA', 'SP');

-- INSERI 8 TELEFONES

INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (1, 498409498904);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (2, 737583738797);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (3, 471379834749);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (4, 741478043722);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (5, 590172509905);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (6, 350912745719);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (7, 847424742784);
INSERT INTO TELEFONES (TELEFONEID, TELEFONE_SOCIO)
VALUES (8, 748714843907);

-- INSERI 1 AUTOR

INSERT INTO AUTORES (ID_AUTORES, NOME, SOBRENOME)
VALUES (1, 'MARCOS', 'SOUZA');

-- INSERI 3 EDITORAS

INSERT INTO EDITORAS (ID_EDITORA, RAZAO_SOCIAL, TELEFONE)
VALUES (1, 'IDE LTDA', 783471335878);
INSERT INTO EDITORAS (ID_EDITORA, RAZAO_SOCIAL, TELEFONE)
VALUES (2, 'ROCCO LTDA', 259384093903);
INSERT INTO EDITORAS (ID_EDITORA, RAZAO_SOCIAL, TELEFONE)
VALUES (3, 'ARQUEIRO LTDA', 3940503839830);

-- INSERI 5 LIVROS

INSERT INTO LIVROS (ID_LIVRO, COD_ISDN, TITULO, ANO_CRIACAO, ANO_PUBLICACAO)
VALUES (1, 0001, 'OLA MUNDO', '1995-05-24', '1995-05-23');
INSERT INTO LIVROS (ID_LIVRO, COD_ISDN, TITULO, ANO_CRIACAO, ANO_PUBLICACAO)
VALUES (2, 0002, 'EM UM MUNDO MELHOR', '2000-05-24', '2002-05-23');
INSERT INTO LIVROS (ID_LIVRO, COD_ISDN, TITULO, ANO_CRIACAO, ANO_PUBLICACAO)
VALUES (3, 0003, 'INTERNET', '2005-05-24', '2006-05-23');
INSERT INTO LIVROS (ID_LIVRO, COD_ISDN, TITULO, ANO_CRIACAO, ANO_PUBLICACAO)
VALUES (4, 0004, 'WEBSITE', '2020-05-24', '2021-05-23');
INSERT INTO LIVROS (ID_LIVRO, COD_ISDN, TITULO, ANO_CRIACAO, ANO_PUBLICACAO)
VALUES (5, 0005, 'MYSQL', '2016-05-24', '2017-05-23');

-- REALIZEI A ATUALIZACAO DA COLUNA LIVROS, ADICIONANDO O COD-AUTOR E COD_EDITORA PARA TODOS OS ID_LIVROS, REALIZANDO DEPOIS O SELECT PARA VERIFICAR SE FOI ATUALIZADO.

UPDATE
	LIVROS
SET
	COD_AUTOR = 1
WHERE
ID_LIVRO > 0 ;   

UPDATE
	LIVROS
SET
	COD_EDITORA = 1
WHERE
ID_LIVRO IN (1,3);

UPDATE
	LIVROS
SET
	COD_EDITORA = 3
WHERE
ID_LIVRO IN (2,4); 

UPDATE
	LIVROS
SET
	COD_EDITORA = 2
WHERE
ID_LIVRO IN (5);  

SELECT * FROM LIVROS 
WHERE ID_LIVRO > 0; 

-- INSERI 5 EXEMPLARES

INSERT INTO EXEMPLARES (ID_EXEMPLAR, COD_LIVRO, SINISTRO)
VALUES (1, 001, 1);
INSERT INTO EXEMPLARES (ID_EXEMPLAR, COD_LIVRO, SINISTRO)
VALUES (2, 002, 1);
INSERT INTO EXEMPLARES (ID_EXEMPLAR, COD_LIVRO, SINISTRO)
VALUES (3, 003, 0);
INSERT INTO EXEMPLARES (ID_EXEMPLAR, COD_LIVRO, SINISTRO)
VALUES (4, 004, 0);
INSERT INTO EXEMPLARES (ID_EXEMPLAR, COD_LIVRO, SINISTRO)
VALUES (5, 005, 1);

-- REALIZEI A SELECT PARA VERIFICAR SE ESTA TUDO OK

SELECT * FROM EXEMPLARES 
WHERE SINISTRO < 2; 

-- INSERI 3 EMPRESTIMOS

INSERT INTO EMPRESTIMOS (CODIGO, CODASSOC, DATA, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO)
VALUES (1, 1, '2010-03-01', '2011-05-01', '2013-03-23');
INSERT INTO EMPRESTIMOS (CODIGO, CODASSOC, DATA, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO)
VALUES (2, 4, '2020-07-01', '2015-8-01', '2018-05-23');
INSERT INTO EMPRESTIMOS (CODIGO, CODASSOC, DATA, PRAZO_DEVOLUCAO, DATA_DEVOLUCAO)
VALUES (3, 2, '2008-06-01', '2022-05-01', '2021-03-23');

-- INSERI 3 REGISTROS EM EMPRESTIMO_EXEMPLARES

INSERT INTO EMPRESTIMO_EXEMPLARES (`ID-EMPRESTIMO_EXEMPLAR`, COD_EMPRESTIMO, COD_EXEMPLAR)
VALUES (1, 3, 2);
INSERT INTO EMPRESTIMO_EXEMPLARES (`ID-EMPRESTIMO_EXEMPLAR`, COD_EMPRESTIMO, COD_EXEMPLAR)
VALUES (2,1,4);
INSERT INTO EMPRESTIMO_EXEMPLARES (`ID-EMPRESTIMO_EXEMPLAR`, COD_EMPRESTIMO, COD_EXEMPLAR)
VALUES (3, 2, 1);

-- EXCLUIR UM ASSOCIADO E VERIFICANDO SE DEU CERTO

DELETE FROM ASSOCIADOS WHERE CODID_ = 3;

SELECT * FROM ASSOCIADOS 
WHERE CODID_ > 0; 

-- TENTANDO EXCLUIR UM LIVRO ONDE UM EXEMPLAR EXISTE NO NOME DO ASSOCIADO QUE FOI EXCLUIDO ACIMA

DELETE FROM LIVROS WHERE CODID_ = 3;

-- ATUALIZANDO O ENDERECO DO ASSOCIADO ID 4, POIS O 3 FOI EXCLUIDO

UPDATE
	ASSOCIADOS
SET
	ENDERECO = 'RUA DAS FLORES 860'
WHERE
CODID_ = 4 ;   
