-- 1 --
insert into 
TB_VENDEDOR (ID_VENDEDOR, NOME, ENDERECO, TELEFONE, CELULAR, EMAIL, CNPJ, NR_CONTRATO, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO, DATA_ENTRADA_SISTEMA, STATUS, DATA_INATIVACAO) values (11,
 'Corretora So Love',
 '33149 New Castle Point',
 '(28)98797-33957',
 '(63)16191-39469',
 'aschindler0@globo.com',
 '17.188.76/2526-85', 
 '05.0872056.79',
 '2020-01-01',
 '2023-06-01',
 '2020-01-01',
 'ATIVO', null);
insert into
 TB_VENDEDOR (ID_VENDEDOR, NOME, ENDERECO, TELEFONE, CELULAR, EMAIL, CNPJ, NR_CONTRATO, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO, DATA_ENTRADA_SISTEMA, STATUS, DATA_INATIVACAO) values (12,
 'BR Corretora',
 '96 Gerald Street',
 '(05)12524-84298',
 '(48)53239-34858',
 'qrodbourne1@yale.edu',
 '07.127.91/1928-59',
 '77.2050132.08',
 '2020-01-01',
 '2023-06-01',
 '2020-01-01',
 'ATIVO',
 null);
 
 -- 2 -- 
 insert into TB_PLANO (ID_PLANO, NOME_PLANO, DESCRICAO_PLANO, DATA_CRIACAO_PLANO, VALOR_PLANO) VALUES (4, 'Plano Integral Dental', 'Plano avançado com cobertura limitada', '2020-03-01', 75);
 insert into TB_PLANO (ID_PLANO, NOME_PLANO, DESCRICAO_PLANO, DATA_CRIACAO_PLANO, VALOR_PLANO) VALUES (5, 'Plano Integral Dental II MAX', 'Plano avançado com cobertura ilimitada', '2020-03-01', 99.99);
 
 -- 3 --
 INSERT INTO TB_HISTORICO_ASSOCIADO_PLANO(ID_HISTORICO_ASSOCIADO_PLANO,
 ID_ASSOCIADO, 
 ID_PLANO,
 DATA_INICIO_VIGENCIA,
 DATA_FIM_VIGENCIA) VALUES (12,
 36,
 (SELECT ID_PLANO_ATUAL FROM TB_ASSOCIADO WHERE ID_ASSOCIADO = 36),
 (SELECT DATA_ENTRADA_SISTEMA FROM TB_ASSOCIADO WHERE ID_ASSOCIADO = 36),
 '2022-01-01');
 
select * from TB_HISTORICO_ASSOCIADO_PLANO;
 
update tb_associado set id_plano_atual = 4 where nome_completo like '%Massimiliano%';
 
select * from TB_ASSOCIADO;
  
-- 4 --
-- select * FROM TB_ASSOCIADO;
-- SELECT *, COUNT(*) FROM TB_ASSOCIADO
-- GROUP BY COD_CARTEIRINHA
-- HAVING COUNT(*) > 1;
 
SELECT * FROM TB_ASSOCIADO WHERE NOME_COMPLETO LIKE 'Lorie Sweating' OR 'Berton Vernall';
 
DELETE FROM TB_ASSOCIADO WHERE COUNT(*);
-- 5 --
SELECT * FROM tb_historico_associado_plano WHERE DATA_FIM_VIGENCIA < DATA_INICIO_VIGENCIA;
  
UPDATE tb_historico_associado_plano SET DATA_FIM_VIGENCIA = '2027-01-01' WHERE DATA_FIM_VIGENCIA < DATA_INICIO_VIGENCIA;
  
SELECT * FROM tb_historico_associado_plano WHERE DATA_FIM_VIGENCIA LIKE '2027-01-01';
    
-- 6 --
SELECT TB_ASSOCIADO.NOME_COMPLETO, tb_associado.ID_ASSOCIADO,
COUNT(*)
FROM TB_ASSOCIADO_TELEFONE
INNER JOIN tb_associado ON tb_associado.ID_ASSOCIADO = tb_associado_telefone.ID_ASSOCIADO
GROUP BY ID_ASSOCIADO
HAVING COUNT(*) > 2
ORDER BY ID_ASSOCIADO;

-- 7 -- 
select * from tb_associado where nome_completo like 'Lorette%';
update tb_associado set nome_completo = 'Lorette
Windibank Jr' where NOME_COMPLETO = 'Lorette Windibank';

-- 8 --
select * from tb_associado_contrato;
insert into TB_ASSOCIADO_CONTRATO (ID_ASSOCIADO_CONTRATO, ID_ASSOCIADO, ID_VENDEDOR, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO) values (12, 36, 11, '2020-01-02', '2022-01-03');
insert into TB_ASSOCIADO_CONTRATO (ID_ASSOCIADO_CONTRATO, ID_ASSOCIADO, ID_VENDEDOR, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO) values (13, 129, 11, '2020-01-02', '2022-01-03');

-- 9 --
alter table tb_associado_contrato add NUM_CONTRATO_FISICO char(20);
insert into TB_ASSOCIADO_CONTRATO (ID_ASSOCIADO_CONTRATO, ID_ASSOCIADO, ID_VENDEDOR, DATA_INICIO_CONTRATO, DATA_FIM_CONTRATO, NUM_CONTRATO_FISICO) values (14, 130, 11, '2020-01-02', '2022-01-03', 'DIGITALHOUSECTDTURM1');