-- DDL PREST SERV
CREATE DATABASE PREST_SERV;
USE PREST_SERV;

CREATE TABLE CLIENTES (
     ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(45),
     SOBRENOME VARCHAR(45),
     CPF VARCHAR(11) NOT NULL,
     RG VARCHAR(9) NOT NULL,
     SENHA VARCHAR(45) NOT NULL,
     USUARIO VARCHAR(45) NOT NULL,
     AVALIACAO VARCHAR(5)
);


CREATE TABLE END_CLIENTE (
     ID_END_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     RUA VARCHAR(150),
     NUMERO VARCHAR(10),
     CEP VARCHAR(8),
     CIDADE VARCHAR(60),
     ESTADO VARCHAR(2),
     BAIRRO VARCHAR(100),
     ID_CLIENTE INT NOT NULL,
     CONSTRAINT FK_END_CLIENTE_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE FATURAS (
     ID_FATURA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     ID_CLIENTE INT NOT NULL,
     DATA_FATURA DATE,
     END_COBR VARCHAR(150),
     CIDADE_COBR VARCHAR(45),
     ESTADO_COBR VARCHAR(6),
     PAIS_COBR VARCHAR(14),
     CEP_COBR VARCHAR(8),
     VALOR_TOTAL DECIMAL(10,2),
     CONSTRAINT FK_FATURAS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE CONTATO_CLIENTE (
     ID_CONTATO_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     TEL VARCHAR(12),
     CEL VARCHAR(13) NOT NULL,
     EMAIL VARCHAR(100) NOT NULL,
     INSTAGRAM VARCHAR(100),
     FACE VARCHAR(100),
     ID_CLIENTE INT NOT NULL,
     CONSTRAINT FK_CONTATO_CLIENTE_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE PAGAMENTOS (
     ID_PAGAMENTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     CREDITO TINYINT,
     DEBITO TINYINT,
     AVISTA TINYINT,
     BOLETO TINYINT,
     PIX TINYINT,
     TRANSF TINYINT,
     ID_CLIENTE INT NOT NULL,
     CONSTRAINT FK_PAGAMENTOS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE EMPRESAS (
    ID_EMPRESA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    RAZAO_SOCIAL VARCHAR(150) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    NOME_FANTASIA VARCHAR(100),
    NOME_RESPONSAVEL VARCHAR(150),
    IE VARCHAR(12) NOT NULL,
    IM VARCHAR(6),
    SOBRE_EMPRESA TEXT,
    ID_CLIENTE INT NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    USUARIO VARCHAR(60) NOT NULL,
    AVALIACAO VARCHAR(5),
    CONSTRAINT FK_EMPRESAS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE)
);

CREATE TABLE SERVICOS (
     ID_SERVICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     FOTO_SERVICO TINYBLOB,
     SERVICO_PRESTADO TEXT,
     ORCAMENTO DECIMAL(10,2),
     DATA_INICIO DATE,
     DATA_TERMINO DATE,
     OBS TEXT,
     AVALIACAO VARCHAR(5),
     ID_CLIENTE INT NOT NULL,
     ID_EMPRESA INT NOT NULL,
     CONSTRAINT FK_SERVICOS_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
     CONSTRAINT FK_SERVICOS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA)
);

CREATE TABLE CONTATO_EMPRESA (
     ID_CONTATO_EMPRESA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     TEL VARCHAR(12),
     CEL VARCHAR(13) NOT NULL,
     EMAIL VARCHAR(100) NOT NULL,
     INSTAGRAM VARCHAR(100),
     FACE VARCHAR(100),
     SITE VARCHAR(255),
     ID_EMPRESA INT NOT NULL,
     CONSTRAINT FK_CONTATO_EMPRESA_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA)
);

CREATE TABLE END_EMPRESA (
     ID_END_EMPRESA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     RUA VARCHAR(150),
     NUMERO VARCHAR(10),
     CEP VARCHAR(8),
     CIDADE VARCHAR(60),
     ESTADO VARCHAR(2),
     BAIRRO VARCHAR(100),
     ID_EMPRESA INT NOT NULL,
     CONSTRAINT FK_END_EMPRESA_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA)
);

CREATE TABLE TIPO_SERVICOS (
     ID_TIPO_SERVICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     PEDREIRO TINYINT,
     JARDINEIRO TINYINT,
     PISCINEIRO TINYINT,
     SEGURANCA TINYINT,
     MOTOBOY TINYINT,
     ENCANADOR TINYINT,
     ID_EMPRESA INT NOT NULL,
     CONSTRAINT FK_TIPO_SERVICOS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA)
);

CREATE TABLE RECEBIMENTO_EMPRESAS (
     ID_RECEBIMENTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     DATA_RECEB DATE,
     BANCO VARCHAR(45),
     ARGENCIA VARCHAR(4) NOT NULL,
     CONTA VARCHAR(5) NOT NULL,
     VALOR_RECEB DECIMAL(10,2),
     ID_EMPRESA INT NOT NULL,
     CONSTRAINT FK_RECEBIMENTO_EMPRESAS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA)
);

CREATE TABLE EMPREGADOS (
     ID_EMPREGADO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
     NOME VARCHAR(45) NOT NULL,
     SOBRENOME VARCHAR(45) NOT NULL,
     CPF VARCHAR(11) NOT NULL,
     ID_EMPRESA INT NOT NULL,
     ID_SERVICO INT NOT NULL,
     DATA_NASC DATE,
     RG VARCHAR(9) NOT NULL,
     SENHA VARCHAR(45) NOT NULL,
     USUARIO VARCHAR(60) NOT NULL,
     CONSTRAINT FK_EMPREGADOS_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA),
     CONSTRAINT FK_EMPREGADOS_SERVICOS FOREIGN KEY (ID_SERVICO) REFERENCES SERVICOS (ID_SERVICO)
);

-- DROP DATABASE PREST_SERV;