-- MODIFICAÇÕES E ALTERAÇÕES
USE PREST_SERV;

-- Atualização de dados em uma das tabelas.
-- Exclusão de dados em uma das tabelas.

-- FOI ALTERADO A EMPRESA QUE CORRESPONDE AO SERVIÇO EXECUTADO

UPDATE
TIPO_SERVICOS
SET
ID_EMPRESA = 3
WHERE
ID_TIPO_SERVICO = 1;

-- FOI ADICIONADO A CATEGORIA AVALIAÇÃO NA TABELA DE EMPREGADOS COMO TAMBÉM AS NOTAS DE CADA EMPREGADO EXISTENTE

ALTER TABLE EMPREGADOS ADD COLUMN AVALIACAO VARCHAR(5);

SELECT * FROM EMPREGADOS;

UPDATE
EMPREGADOS
SET
AVALIACAO = 3
WHERE
ID_EMPREGADO = 1;

UPDATE
EMPREGADOS
SET
AVALIACAO = 5
WHERE
ID_EMPREGADO = 2;

UPDATE
EMPREGADOS
SET
AVALIACAO = 4
WHERE
ID_EMPREGADO = 3;

-- FOI EXCLUIDO UM EMPREADO E INCERIDO OUTRO EMPREGADO

DELETE FROM EMPREGADOS WHERE ID_EMPREGADO = 4;

INSERT INTO EMPREGADOS (NOME, SOBRENOME, CPF, ID_EMPRESA, ID_SERVICO, DATA_NASC, RG, SENHA, USUARIO, AVALIACAO)
VALUES ('RICHARD', 'HENRIQUE', 28394827392, 3, 2, '1980-04-11', 783920937, 'JBFJFEKJBN', 'RICK', 3);

-- Seleção de dados de uma das tabelas
-- FOI VERIFICADO A TABELA CLIENTES
-- COMO TAMBÉM OS VALORES DAS FATURAS, SENDO O MINIMO, MAXIMO E A MÉDIA

SELECT *
FROM CLIENTES;

SELECT 
	MIN(VALOR_TOTAL) AS 'VALOR MINIMO DE UMA FATURA',
    MAX(VALOR_TOTAL) AS 'VALOR MÁXIMO DE UMA FATURA',
    ROUND(AVG(VALOR_TOTAL), 2) AS 'VALOR MÉDIO DAS FATURAS',
    SUM(VALOR_TOTAL) AS 'VALOR TOTAL DAS FATURAS'
FROM FATURAS;

-- FOI FEITO UM RELATÓRIO SOBRE A QUANTIDADE DE CLIENTES QUE POSSIEM EM CADA CIDADE E ESTADO

SELECT
	CIDADE, ESTADO,
    COUNT(*) AS 'QUANTIDADE DE CLIENTES'
FROM END_CLIENTE
GROUP BY
	CIDADE, ESTADO
ORDER BY
	CIDADE DESC;
    
-- Seleção de registros envolvendo join com pelo menos duas tabelas e algum tipo de agregação
-- FOI FEITO UM RELATÓRIO SOBRE AS INFROMAÇÕES DOS CLIENTES COMO ENDEREÇOS, CONTADOS, SERVIÇOS E EMPRESAS QUE CONTRATARAM
-- FOI REALIZANDO TAMBÉM UM RELATÓRIO INFROMANDO A QUANTIDADE DE FATURAS, VALOR MÉDIO E A QUANTIDADE DE CADA TIPO DE PAGAMENTO.

SELECT 
    CONCAT(CLIENTES.NOME, ' ', CLIENTES.SOBRENOME) AS 'CLIENTE',
    CONCAT(END_CLIENTE.RUA, ' , ',
            END_CLIENTE.NUMERO, ' , ',
            END_CLIENTE.CIDADE, ' , ',
            END_CLIENTE.ESTADO) AS 'ENDEREÇO',
	CONCAT(CONTATO_CLIENTE.CEL, ' , ',
           CONTATO_CLIENTE.INSTAGRAM, ' , ',
           CONTATO_CLIENTE.FACE) AS 'CONTATOS, INTAGRAM E FACE',
	CONCAT(SERVICOS.ORCAMENTO, ' , ') AS 'ORÇAMENTO',
    DATE_FORMAT(SERVICOS.DATA_INICIO, '%d/%m/%Y') AS 'DATA INÍCIO',
    DATE_FORMAT(SERVICOS.DATA_TERMINO, '%d/%m/%Y') AS 'DATA TÉRMINO',
    CONCAT(EMPRESAS.RAZAO_SOCIAL, ' , ', EMPRESAS.CNPJ) AS 'EMPRESA E CNPJ'
FROM
    CLIENTES
        INNER JOIN
    END_CLIENTE ON END_CLIENTE.ID_END_CLIENTE = CLIENTES.ID_CLIENTE
        INNER JOIN
	CONTATO_CLIENTE ON CONTATO_CLIENTE.ID_CONTATO_CLIENTE = CLIENTES.ID_CLIENTE
        INNER JOIN
	SERVICOS ON SERVICOS.ID_SERVICO = CLIENTES.ID_CLIENTE
        INNER JOIN
	EMPRESAS ON EMPRESAS.ID_EMPRESA = CLIENTES.ID_CLIENTE
ORDER BY CLIENTES.NOME;

SELECT 
    SUM(PAGAMENTOS.ID_PAGAMENTO) AS 'QUANTIDADE PAGAMENTOS',
    SUM(PAGAMENTOS.CREDITO) AS 'CRÉDITO', 
    SUM(PAGAMENTOS.DEBITO) AS 'DÉBITO', 
    SUM(PAGAMENTOS.AVISTA) AS 'A VISTA',
    SUM(PAGAMENTOS.BOLETO) AS 'BOLETO',
	SUM(PAGAMENTOS.PIX) AS 'PIX',
	SUM(PAGAMENTOS.TRANSF) AS 'TRANSFERÊNCIA',
    ROUND(AVG(VALOR_TOTAL), 2) AS 'VALOR MÉDIO DAS FATURAS'
FROM
    PAGAMENTOS
        INNER JOIN
    CLIENTES ON CLIENTES.ID_CLIENTE = PAGAMENTOS.ID_PAGAMENTO
        INNER JOIN
    FATURAS ON FATURAS.ID_FATURA = CLIENTES.ID_CLIENTE;

SELECT * FROM PAGAMENTOS;