-- DML - CONJUNTO DE INSTRUÇÕES RESPONSÁVEIS PELA MANIPULAÇÃO E GERENCIAMENTO DOS DADOS/REGISTROS
-- SELECT - INSTRUÇÃO RESPONSÁVEL POR CONSULTAR OS DADOS EM UMA TABELA
SELECT NR_CARTEIRINHA FROM PACIENTE;
SELECT * FROM PACIENTE;

-- INSERT - INSTRUÇÃO RESPONSÁVEL POR INSERIR UM REGISTRO EM UMA TABELA
INSERT INTO PACIENTE (ID_PACIENTE, NR_CARTEIRINHA, NOME, SOBRENOME)
VALUES (1, 123, 'Daniela', 'Coltri');

-- UPDATE - INSTRUÇÃO RESPONSÁVEL POR ATUALIZAR UM REGISTRO EM UMA TABELA
UPDATE
	PACIENTE
SET
	NOME = 'Daniela',
    SOBRENOME = 'Coltri'
WHERE
	ID_PACIENTE = 3;

-- DELETE - INSTRUÇÃO RESPONSÁVEL POR REMOVER UM REGISTRO EM UMA TABELA
DELETE FROM PACIENTE WHERE ID_PACIENTE = 1;